# Generated by Django 3.2.6 on 2021-09-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
