# Generated by Django 3.2.6 on 2021-09-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210916_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('view_student_account', 'can view student account'), ('edit_student_account', 'can edit student account')]},
        ),
    ]
