# Generated by Django 3.2.6 on 2021-09-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
