# Generated by Django 3.2.6 on 2021-09-23 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_indentity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Indentity',
            new_name='Identity',
        ),
    ]
