# Generated by Django 3.2.7 on 2021-11-03 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_rename_indentity_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('property_type', models.CharField(choices=[('COMMUNE', 'Commune'), ('APARTMENT', 'Apartment'), ('FLAT', 'flat')], max_length=9)),
                ('university_catered', models.CharField(choices=[('UJ', 'UJ'), ('NWU', 'NWU'), ('TUT', 'TUT'), ('WITS', 'WITS'), ('UP', 'WITS'), ('CUT', 'CUT'), ('VUT', 'VUT'), ('UWC', 'UWC'), ('UFS', 'UFS')], max_length=4)),
                ('address', models.TextField()),
                ('province', models.CharField(max_length=20)),
                ('laundromat', models.BooleanField()),
                ('unlimited_wifi', models.BooleanField()),
                ('transport', models.BooleanField()),
                ('free_electricity', models.BooleanField()),
                ('single_male', models.IntegerField()),
                ('single_female', models.IntegerField()),
                ('sharing_female', models.IntegerField()),
                ('sharing_male', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
