# Generated by Django 3.2.7 on 2021-11-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_student_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
