# Generated by Django 3.2.7 on 2021-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20211201_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='kitchen_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='main_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='room_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='study_room_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
