# Generated by Django 3.2.7 on 2021-12-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_addproperty_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproperty',
            name='main_picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
