# Generated by Django 3.2.7 on 2021-12-06 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0020_auto_20211206_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funding', models.CharField(choices=[('NSFAS', 'NSFAS'), ('BURSARY', 'Bursary'), ('SELF FUNDED', 'Self Funded ')], max_length=11)),
                ('room_type', models.CharField(choices=[('SHARING', 'Sharing'), ('SINGLE', 'Single')], max_length=7)),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('PENDING', 'Pending')], max_length=8)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.addproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
