# Generated by Django 3.2.7 on 2021-12-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='accreditation_letter',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='addproperty',
            name='lease',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
